### ISSUE TITLE
PyAAF2 performance seems to be about 4x slower than PyAAF1

### ISSUE THREAD

**Issue by ssteinbach** [markreidvfx/pyaaf2#22]
I've been looking at the performance of PyAAF2 vs PyAAF1, and it unfortunately looks like PyAAF2 is about 4x slower.  For example, this file:
https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/opentimelineio_contrib/adapters/tests/sample_data/linear_speed_effects.aaf

Takes about 4x as long to read with PyAAF2.  Profiling suggests a couple things might be going on but a clear winner doesn't obviously jump out to me...

Here is the script I was using to profile (via the OTIO adapter):
```python
#!/usr/bin/env python
import cProfile
import StringIO
import pstats
import opentimelineio as otio

pr = cProfile.Profile()
pr.enable()
tl = otio.adapters.read_from_file(
    "opentimelineio_contrib/adapters/tests/sample_data/linear_speed_effects.aaf"
)
pr.disable()
s = StringIO.StringIO()
sortby = 'cumulative'
# sortby = 'tottime'
ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
ps.print_stats()
print s.getvalue()
```

Any suggestions or thoughts on what might be done to improve performance in PyAAF2?

Thanks!

**Comment by markreidvfx** [comment]
Only 4x? I thought it might be more slower!! :p Sadly performance is one of the trade offs in going pure python sometimes.

One thing I quickly noticed is _get_parameter() function is expensive. Generating once and reusing that dictionary is a small speed up. dictionary.lookup_def is slow and that might be partly why.

That's probably not the big speed up your looking for though. In order to get a lot faster, I think some code would have be converted to C/C++.  I was thinking of having some optional accelerated cython modules, just not entirely sure what is the best module to start.  cfb.py seems like a good place to start but it also seems to me that a lot of the time is also spent in the property classes.

some other things I've notices is PyPy isn't much faster is this case :s, but python3 is.

**Comment by markreidvfx** [comment]
A quick cython test
`cythonize -i -b ./aaf2`
That gives me a 1.4x speed up on this test from pure python. and thats without static typing anything yet.

**Comment by markreidvfx** [comment]
The performance of `dictionary.lookup_def` should be much better now. It was actually slowing down things a lot more then I thought.  Also experimenting using `mmap` in cfb.py, getting a little better performance in some cases.

**Comment by markreidvfx** [comment]
I've done a pass of further optimizations and have improved performance on this test case approximately 2X. Still looking into further optimizations.

**Comment by MartinDelille** [comment]
Is performance really a big issue? 2X seems totally acceptable for a Python version.

**Comment by markreidvfx** [comment]
Read performance should only be approximately 1.4X slower with python2.7 then pyaaf1 now!  python3.7 in some cases is as fast or faster then pyaaf1 too. 

@MartinDelille it depends what you need to do. Its been a issue for me on really large files, a 500mb files was taking my laptop 40mins to walk through with through :S.

**Comment by ssteinbach** [comment]
Awesome!

Yeah, feature length AAFs get big fast, and ideally they'd still be quickly readable.

**Comment by ssteinbach** [comment]
Should I close this issue?  Or update the title?  I can leave it open if you want to still work on this.

**Comment by markreidvfx** [comment]
I'm pretty happy with the improvements I made so far. I was hoping to hear if its improved on you end.  read performance should be equal to pyaaf1 now, in some cases its faster, especially with the latest python3.  Memory usage is also drastically smaller then pyaaf1. On large files is can be as big as 20X less memory.
