### ISSUE TITLE
"pct_parser" not implemented in PyAAF2

### ISSUE THREAD

**Issue by conor-hodder** [markreidvfx/pyaaf2#59]
I am attempting to re-implement the example from PyAAF to "dump avid titles" and could not locate the equivalent function 'pct_parser' in the new module. Is there a reason this has not been added? 

Copying the code from PyAAF appears to work as intended (in my specific example). Just wanted to check if there was a known limitation or reason as to why it wasn't ported yet considering it is pure python in the original version

**Comment by markreidvfx** [comment]
I have much more up to date code for parsing avid titles in separate repository
https://github.com/markreidvfx/pct_titles

It could really use some more work, cleanup and tests. I just pushed some of my latest updates from a while ago when I was messing with it if you'd like to take a look. I was thinking keeping it separate because It also relevant my [pyavb](https://github.com/markreidvfx/pyavb) project.  But I'd consider merging it into pyaaf2, if someone finds it useful or submits a pull request

**Comment by conor-hodder** [comment]
Nope, that's perfect - thank you.
